#
# Table structure for table 'country'
#

DROP TABLE city;

CREATE TABLE  city (
ID BIGINT UNSIGNED NOT NULL,
abbr varchar(3),
name varchar(100),
PRIMARY KEY (ID) 
);

insert into city(ID, abbr, name) values (1,"ABZ","Aberdeen");
insert into city(ID, abbr, name) values (2,"ABJ","Abidjan");
insert into city(ID, abbr, name) values (3,"AUH","Abu Dhabi");
insert into city(ID, abbr, name) values (4,"ACA","Acapulco");
insert into city(ID, abbr, name) values (5,"ADA","Adana");
insert into city(ID, abbr, name) values (6,"ADL","Adelaide");
insert into city(ID, abbr, name) values (7,"ADE","Aden");
insert into city(ID, abbr, name) values (8,"AGA","Agadir");
insert into city(ID, abbr, name) values (9,"AJA","Ajaccio");
insert into city(ID, abbr, name) values (10,"ABQ","Albuquerque");
insert into city(ID, abbr, name) values (11,"ALY","Alexandria");
insert into city(ID, abbr, name) values (12,"HBE","Alexandria/HBE");
insert into city(ID, abbr, name) values (13,"AHO","Alghero");
insert into city(ID, abbr, name) values (14,"ALC","Alicante");
insert into city(ID, abbr, name) values (15,"ALA","Almaty");
insert into city(ID, abbr, name) values (16,"LEI","Almeria");
insert into city(ID, abbr, name) values (17,"AOC","Altenburg");
insert into city(ID, abbr, name) values (18,"AMQ","Ambon");
insert into city(ID, abbr, name) values (19,"AMM","Amman");
insert into city(ID, abbr, name) values (20,"AMS","Amsterdam");
insert into city(ID, abbr, name) values (21,"ANC","Anchorage");
insert into city(ID, abbr, name) values (22,"AOI","Ancona");
insert into city(ID, abbr, name) values (23,"ASD","Andros");
insert into city(ID, abbr, name) values (24,"AXA","Anguilla");
insert into city(ID, abbr, name) values (25,"ANK","Ankara");
insert into city(ID, abbr, name) values (26,"ESB","Ankara-Esenboga");
insert into city(ID, abbr, name) values (27,"AYT","Antalya");
insert into city(ID, abbr, name) values (28,"TNR","Antananarivo");
insert into city(ID, abbr, name) values (29,"ANU","Antigua");
insert into city(ID, abbr, name) values (30,"ANR","Antwerpen");
insert into city(ID, abbr, name) values (31,"APW","Apia");
insert into city(ID, abbr, name) values (32,"AQJ","Aqaba");
insert into city(ID, abbr, name) values (33,"AJU","Aracaju");
insert into city(ID, abbr, name) values (34,"ARW","Arad");
insert into city(ID, abbr, name) values (35,"GPA","Araxos");
insert into city(ID, abbr, name) values (36,"ACE","Arrecife");
insert into city(ID, abbr, name) values (37,"AUA","Aruba");
insert into city(ID, abbr, name) values (38,"JRO","Arusha");
insert into city(ID, abbr, name) values (39,"ASB","Ashgabat");
insert into city(ID, abbr, name) values (40,"ASE","Aspen");
insert into city(ID, abbr, name) values (41,"ASW","Assuan");
insert into city(ID, abbr, name) values (42,"ATH","Athen");
insert into city(ID, abbr, name) values (43,"ATL","Atlanta");
insert into city(ID, abbr, name) values (44,"AKL","Auckland");
insert into city(ID, abbr, name) values (45,"AGB","Augsburg");
insert into city(ID, abbr, name) values (46,"AUS","Austin");
insert into city(ID, abbr, name) values (47,"RAR","Avarua");
insert into city(ID, abbr, name) values (48,"BAH","Bahrain");
insert into city(ID, abbr, name) values (49,"BPN","Balikpapan");
insert into city(ID, abbr, name) values (50,"BWI","Baltimore");
insert into city(ID, abbr, name) values (51,"BKK","Bangkok");
insert into city(ID, abbr, name) values (52,"BJL","Banjul");
insert into city(ID, abbr, name) values (53,"BGI","Barbados");
insert into city(ID, abbr, name) values (54,"BBQ","Barbuda");
insert into city(ID, abbr, name) values (55,"BCN","Barcelona");
insert into city(ID, abbr, name) values (56,"BLA","Barcelona");
insert into city(ID, abbr, name) values (57,"BRI","Bari");
insert into city(ID, abbr, name) values (58,"BSL","Basel");
insert into city(ID, abbr, name) values (59,"BIA","Bastia");
insert into city(ID, abbr, name) values (60,"BTR","Baton Rouge");
insert into city(ID, abbr, name) values (61,"BYU","Bayreuth");
insert into city(ID, abbr, name) values (62,"BVA","Beauvais-Tille");
insert into city(ID, abbr, name) values (63,"BEY","Beirut");
insert into city(ID, abbr, name) values (64,"BFS","Belfast");
insert into city(ID, abbr, name) values (65,"BZE","Belize City");
insert into city(ID, abbr, name) values (66,"BQU","Bequia");
insert into city(ID, abbr, name) values (67,"BCE","Berenice");
insert into city(ID, abbr, name) values (68,"BGY","Bergamo");
insert into city(ID, abbr, name) values (69,"BGO","Bergen");
insert into city(ID, abbr, name) values (70,"BER","Berlin");
insert into city(ID, abbr, name) values (71,"SXF","Berlin-Sch\u00F6nefeld");
insert into city(ID, abbr, name) values (72,"TXL","Berlin-Tegel");
insert into city(ID, abbr, name) values (73,"THF","Berlin-Tempelhof");
insert into city(ID, abbr, name) values (74,"BDA","Bermuda");
insert into city(ID, abbr, name) values (75,"BRN","Bern");
insert into city(ID, abbr, name) values (76,"BIQ","Biarritz");
insert into city(ID, abbr, name) values (77,"BIO","Bilbao");
insert into city(ID, abbr, name) values (78,"FRU","Bishkek");
insert into city(ID, abbr, name) values (79,"BIS","Bismarck");
insert into city(ID, abbr, name) values (80,"BVC","Boavista");
insert into city(ID, abbr, name) values (81,"BOO","Bodo");
insert into city(ID, abbr, name) values (82,"BJV","Bodrum");
insert into city(ID, abbr, name) values (83,"BXN","Bodrum");
insert into city(ID, abbr, name) values (84,"BOG","Bogota");
insert into city(ID, abbr, name) values (85,"TAG","Bohol");
insert into city(ID, abbr, name) values (86,"BLQ","Bologna");
insert into city(ID, abbr, name) values (87,"FRL","Bologna-Forli");
insert into city(ID, abbr, name) values (88,"BOM","Bombay");
insert into city(ID, abbr, name) values (89,"BNR","Bonaire (BNR)");
insert into city(ID, abbr, name) values (90,"BON","Bonaire");
insert into city(ID, abbr, name) values (91,"BOB","Bora Bora");
insert into city(ID, abbr, name) values (92,"BOD","Bordeaux");
insert into city(ID, abbr, name) values (93,"BOS","Boston");
insert into city(ID, abbr, name) values (94,"BOH","Bournemouth");
insert into city(ID, abbr, name) values (95,"BWK","Brac");
insert into city(ID, abbr, name) values (96,"BDL","Bradley-International");
insert into city(ID, abbr, name) values (97,"BTS","Bratislava");
insert into city(ID, abbr, name) values (98,"BWE","Braunschweig");
insert into city(ID, abbr, name) values (99,"BRE","Bremen");
insert into city(ID, abbr, name) values (100,"BES","Brest");
insert into city(ID, abbr, name) values (101,"BDS","Brindisi");
insert into city(ID, abbr, name) values (102,"BNE","Brisbane");
insert into city(ID, abbr, name) values (103,"BWN","Brunei");
insert into city(ID, abbr, name) values (104,"BRU","Br\u00FCssel");
insert into city(ID, abbr, name) values (105,"BUD","Budapest");
insert into city(ID, abbr, name) values (106,"BUE","Buenos Aires");
insert into city(ID, abbr, name) values (107,"EZE","Buenos Aires/EZE");
insert into city(ID, abbr, name) values (108,"BUH","Bukarest");
insert into city(ID, abbr, name) values (109,"BOJ","Burgas");
insert into city(ID, abbr, name) values (110,"BTV","Burlington");
insert into city(ID, abbr, name) values (111,"CAG","Cagliari");
insert into city(ID, abbr, name) values (112,"CNS","Cairns");
insert into city(ID, abbr, name) values (113,"YYC","Calgary");
insert into city(ID, abbr, name) values (114,"CLY","Calvi");
insert into city(ID, abbr, name) values (115,"CMW","Camaguey");
insert into city(ID, abbr, name) values (116,"CUN","Cancun");
insert into city(ID, abbr, name) values (117,"CIW","Canouan Island");
insert into city(ID, abbr, name) values (118,"CSK","Cap Skirring");
insert into city(ID, abbr, name) values (119,"CCS","Caracas");
insert into city(ID, abbr, name) values (120,"CWL","Cardiff");
insert into city(ID, abbr, name) values (121,"CRU","Carriacou");
insert into city(ID, abbr, name) values (122,"CTG","Cartagena");
insert into city(ID, abbr, name) values (123,"CAS","Casablanca (CAS)");
insert into city(ID, abbr, name) values (124,"CMN","Casablanca");
insert into city(ID, abbr, name) values (125,"CTA","Catania");
insert into city(ID, abbr, name) values (126,"MPH","Caticlan(Boracay)");
insert into city(ID, abbr, name) values (127,"TBI","Cat Island");
insert into city(ID, abbr, name) values (128,"CYB","Cayman Brac");
insert into city(ID, abbr, name) values (129,"CCC","Cayo Coco");
insert into city(ID, abbr, name) values (130,"CYO","Cayo Largo");
insert into city(ID, abbr, name) values (131,"CEB","Cebu");
insert into city(ID, abbr, name) values (132,"CHQ","Chania");
insert into city(ID, abbr, name) values (133,"CHS","Charleston");
insert into city(ID, abbr, name) values (134,"CRW","Charleston");
insert into city(ID, abbr, name) values (135,"CLT","Charlotte");
insert into city(ID, abbr, name) values (136,"CHO","Charlottesville");
insert into city(ID, abbr, name) values (137,"YYG","Charlottetown");
insert into city(ID, abbr, name) values (138,"CHA","Chattanooga");
insert into city(ID, abbr, name) values (139,"CDF","Ch.-de-Gaulle CDF");
insert into city(ID, abbr, name) values (140,"CDL","Ch.-de-Gaulle CDL");
insert into city(ID, abbr, name) values (141,"CJU","Cheju");
insert into city(ID, abbr, name) values (142,"CNX","Chiang Mai");
insert into city(ID, abbr, name) values (143,"CEI","Chiang Rai");
insert into city(ID, abbr, name) values (144,"CHI","Chicago (CHI)");
insert into city(ID, abbr, name) values (145,"ORD","Chicago O\u0180Hare (ORD)");
insert into city(ID, abbr, name) values (146,"HIN","Chinju");
insert into city(ID, abbr, name) values (147,"JKH","Chios");
insert into city(ID, abbr, name) values (148,"CKG","Chongqing");
insert into city(ID, abbr, name) values (149,"CHC","Christchurch");
insert into city(ID, abbr, name) values (150,"AVI","Ciego de Avila");
insert into city(ID, abbr, name) values (151,"CVG","Cincinnati");
insert into city(ID, abbr, name) values (152,"CFE","Clermont-Ferrand");
insert into city(ID, abbr, name) values (153,"CLJ","Cluj");
insert into city(ID, abbr, name) values (154,"COK","Cochin");
insert into city(ID, abbr, name) values (155,"CMB","Colombo");
insert into city(ID, abbr, name) values (156,"CAE","Columbia");
insert into city(ID, abbr, name) values (157,"CMH","Columbus");
insert into city(ID, abbr, name) values (158,"CON","Concord");
insert into city(ID, abbr, name) values (159,"CND","Constanza");
insert into city(ID, abbr, name) values (160,"ORK","Cork");
insert into city(ID, abbr, name) values (161,"CZM","Cozumel");
insert into city(ID, abbr, name) values (162,"CUM","Cumana");
insert into city(ID, abbr, name) values (163,"CUR","Curacao");
insert into city(ID, abbr, name) values (164,"DUS","D\u00FCsseldorf");
insert into city(ID, abbr, name) values (165,"DGA","Dagriga");
insert into city(ID, abbr, name) values (166,"DKR","Dakar");
insert into city(ID, abbr, name) values (167,"DLM","Dalaman");
insert into city(ID, abbr, name) values (168,"DFW","Dallas-Fort Worth");
insert into city(ID, abbr, name) values (169,"DAM","Damaskus");
insert into city(ID, abbr, name) values (170,"GDN","Danzig");
insert into city(ID, abbr, name) values (171,"DAR","Dar es Salam");
insert into city(ID, abbr, name) values (172,"DRW","Darwin");
insert into city(ID, abbr, name) values (173,"DVO","Davao");
insert into city(ID, abbr, name) values (174,"DAB","Daytona Beach");
insert into city(ID, abbr, name) values (175,"DEL","Delhi");
insert into city(ID, abbr, name) values (176,"DAD","Denang");
insert into city(ID, abbr, name) values (177,"DPS","Denpasar");
insert into city(ID, abbr, name) values (178,"DEN","Denver");
insert into city(ID, abbr, name) values (179,"ZCU","Detmold");
insert into city(ID, abbr, name) values (180,"DET","Detroit-City");
insert into city(ID, abbr, name) values (181,"DTW","Detroit");
insert into city(ID, abbr, name) values (182,"DTT","Detroit-Metropolitan");
insert into city(ID, abbr, name) values (183,"DPL","Dipolog");
insert into city(ID, abbr, name) values (184,"DJE","Djerba");
insert into city(ID, abbr, name) values (185,"DOH","Doha");
insert into city(ID, abbr, name) values (186,"DOM","Dominica");
insert into city(ID, abbr, name) values (187,"DTM","Dortmund");
insert into city(ID, abbr, name) values (188,"YUL","Dorval International");
insert into city(ID, abbr, name) values (189,"DRS","Dresden");
insert into city(ID, abbr, name) values (190,"DXB","Dubai");
insert into city(ID, abbr, name) values (191,"DUB","Dublin");
insert into city(ID, abbr, name) values (192,"DBV","Dubrovnik");
insert into city(ID, abbr, name) values (193,"DUR","Durban");
insert into city(ID, abbr, name) values (194,"NRN","D\u00FCsseldorf-Niederrhein");
insert into city(ID, abbr, name) values (195,"EMA","East Midlands");
insert into city(ID, abbr, name) values (196,"EDI","Edinburgh");
insert into city(ID, abbr, name) values (197,"YEG","Edmonton");
insert into city(ID, abbr, name) values (198,"EGS","Egilsstadir");
insert into city(ID, abbr, name) values (199,"ETH","Eilat");
insert into city(ID, abbr, name) values (200,"VDA","Eilat-Uvda");
insert into city(ID, abbr, name) values (201,"EIN","Eindhoven");
insert into city(ID, abbr, name) values (202,"EBA","Elba");
insert into city(ID, abbr, name) values (203,"ENS","Enschede");
insert into city(ID, abbr, name) values (204,"ECN","Ercan");
insert into city(ID, abbr, name) values (205,"ERF","Erfurt");
insert into city(ID, abbr, name) values (206,"VDB","Fagerness");
insert into city(ID, abbr, name) values (207,"FAI","Fairbanks");
insert into city(ID, abbr, name) values (208,"FAO","Faro");
insert into city(ID, abbr, name) values (209,"FAL","Faro Linie");
insert into city(ID, abbr, name) values (210,"FZL","Faro(Linie)");
insert into city(ID, abbr, name) values (211,"FEZ","Fes");
insert into city(ID, abbr, name) values (212,"FSC","Figari");
insert into city(ID, abbr, name) values (213,"FLR","Florenz");
insert into city(ID, abbr, name) values (214,"FOR","Fortaleza");
insert into city(ID, abbr, name) values (215,"FDF","Fort de France");
insert into city(ID, abbr, name) values (216,"FLL","Fort Lauderdale");
insert into city(ID, abbr, name) values (217,"FMY","Fort Myers");
insert into city(ID, abbr, name) values (218,"RSW","Fort Myers");
insert into city(ID, abbr, name) values (219,"FRA","Frankfurt");
insert into city(ID, abbr, name) values (220,"FPO","Freeport");
insert into city(ID, abbr, name) values (221,"FDH","Friedrichshafen");
insert into city(ID, abbr, name) values (222,"FUE","Fuerteventura");
insert into city(ID, abbr, name) values (223,"FNC","Funchal");
insert into city(ID, abbr, name) values (224,"GOT","G\u00F6teborg");
insert into city(ID, abbr, name) values (225,"GSE","G\u00F6teborg (Saeve)");
insert into city(ID, abbr, name) values (226,"GBE","Gaborone");
insert into city(ID, abbr, name) values (227,"GBN","Gaborone");
insert into city(ID, abbr, name) values (228,"GWY","Galway");
insert into city(ID, abbr, name) values (229,"GAN","Gan");
insert into city(ID, abbr, name) values (230,"GZT","Gaziantep");
insert into city(ID, abbr, name) values (231,"GVA","Genf");
insert into city(ID, abbr, name) values (232,"GOA","Genova");
insert into city(ID, abbr, name) values (233,"GGT","Georgetown");
insert into city(ID, abbr, name) values (234,"GRO","Gerona");
insert into city(ID, abbr, name) values (235,"GLA","Glasgow");
insert into city(ID, abbr, name) values (236,"PIK","Glasgow-Prestwick");
insert into city(ID, abbr, name) values (237,"GOI","Goa");
insert into city(ID, abbr, name) values (238,"GOH","Godthab");
insert into city(ID, abbr, name) values (239,"GHB","Governor's Harbour");
insert into city(ID, abbr, name) values (240,"GBI","Grand Bahama");
insert into city(ID, abbr, name) values (241,"GCM","Grand Cayman");
insert into city(ID, abbr, name) values (242,"GFK","Grand Forks");
insert into city(ID, abbr, name) values (243,"GRZ","Graz");
insert into city(ID, abbr, name) values (244,"TCB","Green Turtle Bay");
insert into city(ID, abbr, name) values (245,"GND","Grenada");
insert into city(ID, abbr, name) values (246,"GRQ","Groningen");
insert into city(ID, abbr, name) values (247,"GUM","Guam");
insert into city(ID, abbr, name) values (248,"GUA","Guatemala");
insert into city(ID, abbr, name) values (249,"GYM","Guayamas");
insert into city(ID, abbr, name) values (250,"GYE","Guayaquil");
insert into city(ID, abbr, name) values (251,"GCI","Guernsey");
insert into city(ID, abbr, name) values (252,"GUC","Gunnisson");
insert into city(ID, abbr, name) values (253,"HHN","Hahn");
insert into city(ID, abbr, name) values (254,"HAI","Hainan");
insert into city(ID, abbr, name) values (255,"YHZ","Halifax");
insert into city(ID, abbr, name) values (256,"HAM","Hamburg");
insert into city(ID, abbr, name) values (257,"HTI","Hamilton Island");
insert into city(ID, abbr, name) values (258,"YHM","Hamilton");
insert into city(ID, abbr, name) values (259,"HAJ","Hannover");
insert into city(ID, abbr, name) values (260,"HAN","Hanoi");
insert into city(ID, abbr, name) values (261,"HRE","Harare");
insert into city(ID, abbr, name) values (262,"MDT","Harrisburg");
insert into city(ID, abbr, name) values (263,"HFD","Hartford-Brainard-Airport");
insert into city(ID, abbr, name) values (264,"HAV","Havanna");
insert into city(ID, abbr, name) values (265,"HIS","Hayman Island");
insert into city(ID, abbr, name) values (266,"HEL","Helsinki");
insert into city(ID, abbr, name) values (267,"HER","Heraklion");
insert into city(ID, abbr, name) values (268,"ILO","Hilo");
insert into city(ID, abbr, name) values (269,"HHH","Hilton Head");
insert into city(ID, abbr, name) values (270,"HBA","Hobart");
insert into city(ID, abbr, name) values (271,"HOQ","Hof");
insert into city(ID, abbr, name) values (272,"HOG","Holguin");
insert into city(ID, abbr, name) values (273,"HKG","Hongkong");
insert into city(ID, abbr, name) values (274,"HIR","Honiara");
insert into city(ID, abbr, name) values (275,"HNL","Honolulu");
insert into city(ID, abbr, name) values (276,"HOR","Horta");
insert into city(ID, abbr, name) values (277,"HKN","Hoskins");
insert into city(ID, abbr, name) values (278,"HOU","Houston");
insert into city(ID, abbr, name) values (279,"HUH","Huahine");
insert into city(ID, abbr, name) values (280,"HHQ","Hua Hin");
insert into city(ID, abbr, name) values (281,"HUX","Huatulco");
insert into city(ID, abbr, name) values (282,"HRG","Hurghada");
insert into city(ID, abbr, name) values (283,"FRM","Ibiza / FRM");
insert into city(ID, abbr, name) values (284,"IBZ","Ibiza");
insert into city(ID, abbr, name) values (285,"UNA","Ilha Commandatuba");
insert into city(ID, abbr, name) values (286,"IOS","Ilheus");
insert into city(ID, abbr, name) values (287,"IND","Indianapolis");
insert into city(ID, abbr, name) values (288,"INN","Innsbruck");
insert into city(ID, abbr, name) values (289,"INV","Inverness");
insert into city(ID, abbr, name) values (290,"IST","Istanbul");
insert into city(ID, abbr, name) values (291,"IVL","Ivalu");
insert into city(ID, abbr, name) values (292,"ADB","Izmir");
insert into city(ID, abbr, name) values (293,"JAC","Jackson");
insert into city(ID, abbr, name) values (294,"JAN","Jackson");
insert into city(ID, abbr, name) values (295,"JAX","Jacksonville");
insert into city(ID, abbr, name) values (296,"CGK","Jakarta");
insert into city(ID, abbr, name) values (297,"JKT","Jakarta");
insert into city(ID, abbr, name) values (298,"DJJ","Jayapura");
insert into city(ID, abbr, name) values (299,"JED","Jeddah");
insert into city(ID, abbr, name) values (300,"XRY","Jerez");
insert into city(ID, abbr, name) values (301,"JER","Jersey");
insert into city(ID, abbr, name) values (302,"JNB","Johannesburg");
insert into city(ID, abbr, name) values (303,"JYV","Jyv\u00E4skyl\u00E4");
insert into city(ID, abbr, name) values (304,"CAI","Kairo");
insert into city(ID, abbr, name) values (305,"KLX","Kalamata");
insert into city(ID, abbr, name) values (306,"KLO","Kalibo");
insert into city(ID, abbr, name) values (307,"KGD","Kaliningrad");
insert into city(ID, abbr, name) values (308,"KAG","Kangung");
insert into city(ID, abbr, name) values (309,"KHH","Kaohsiung");
insert into city(ID, abbr, name) values (310,"CPT","Kapstadt");
insert into city(ID, abbr, name) values (311,"FKB","Karlsruhe Baden-Baden");
insert into city(ID, abbr, name) values (312,"AOK","Karpathos");
insert into city(ID, abbr, name) values (313,"KSF","Kassel-Calden");
insert into city(ID, abbr, name) values (314,"KTM","Kathmandu");
insert into city(ID, abbr, name) values (315,"KTW","Kattowitz");
insert into city(ID, abbr, name) values (316,"LIH","Kauai");
insert into city(ID, abbr, name) values (317,"KVA","Kavalla");
insert into city(ID, abbr, name) values (318,"KVG","Kavieng");
insert into city(ID, abbr, name) values (319,"ASR","Kayseri");
insert into city(ID, abbr, name) values (320,"EFL","Kefalonia");
insert into city(ID, abbr, name) values (321,"YLW","Kelowna");
insert into city(ID, abbr, name) values (322,"KIR","Kerry");
insert into city(ID, abbr, name) values (323,"EYW","Key West");
insert into city(ID, abbr, name) values (324,"KEL","Kiel");
insert into city(ID, abbr, name) values (325,"IEV","Kiew");
insert into city(ID, abbr, name) values (326,"KIN","Kingston");
insert into city(ID, abbr, name) values (327,"KTT","Kittila");
insert into city(ID, abbr, name) values (328,"KLU","Klagenfurt");
insert into city(ID, abbr, name) values (329,"NOC","Knock");
insert into city(ID, abbr, name) values (330,"SMU","Koh Samui");
insert into city(ID, abbr, name) values (331,"USM","Koh Samui (USM)");
insert into city(ID, abbr, name) values (332,"CGN","K\u00F6ln");
insert into city(ID, abbr, name) values (333,"KOA","Kona");
insert into city(ID, abbr, name) values (334,"CPH","Kopenhagen");
insert into city(ID, abbr, name) values (335,"CFU","Korfu");
insert into city(ID, abbr, name) values (336,"KGS","Kos");
insert into city(ID, abbr, name) values (337,"BKI","Kota Kinabalu");
insert into city(ID, abbr, name) values (338,"KBV","Krabi");
insert into city(ID, abbr, name) values (339,"KRK","Krk");
insert into city(ID, abbr, name) values (340,"KUL","Kuala Lumpur");
insert into city(ID, abbr, name) values (341,"KUA","Kuantan");
insert into city(ID, abbr, name) values (342,"KCH","Kuching");
insert into city(ID, abbr, name) values (343,"KUV","Kunsan");
insert into city(ID, abbr, name) values (344,"KAO","Kuusamo");
insert into city(ID, abbr, name) values (345,"KWI","Kuwait-City");
insert into city(ID, abbr, name) values (346,"KWJ","Kwangju");
insert into city(ID, abbr, name) values (347,"LGG","L\u00FCttich");
insert into city(ID, abbr, name) values (348,"LKL","Lakselv");
insert into city(ID, abbr, name) values (349,"SUF","Lamezia-Terme");
insert into city(ID, abbr, name) values (350,"LMP","Lampedusa");
insert into city(ID, abbr, name) values (351,"LNY","Lanai");
insert into city(ID, abbr, name) values (352,"LGK","Langkawi");
insert into city(ID, abbr, name) values (353,"SPC","La Palma");
insert into city(ID, abbr, name) values (354,"LAP","La Paz");
insert into city(ID, abbr, name) values (355,"LPB","La Paz");
insert into city(ID, abbr, name) values (356,"LCA","Larnaca");
insert into city(ID, abbr, name) values (357,"LCL","Larnaca Linie");
insert into city(ID, abbr, name) values (358,"LZL","Larnaca(Linie)");
insert into city(ID, abbr, name) values (359,"LRM","La Romana");
insert into city(ID, abbr, name) values (360,"LPA","Las Palmas");
insert into city(ID, abbr, name) values (361,"LAS","Las Vegas");
insert into city(ID, abbr, name) values (362,"MLA","La Valetta");
insert into city(ID, abbr, name) values (363,"LEJ","Leipzig");
insert into city(ID, abbr, name) values (364,"LXS","Lemnos");
insert into city(ID, abbr, name) values (365,"LRS","Leros");
insert into city(ID, abbr, name) values (366,"MJT","Lesbos");
insert into city(ID, abbr, name) values (367,"LSS","Les Saintes");
insert into city(ID, abbr, name) values (368,"LEX","Lexington");
insert into city(ID, abbr, name) values (369,"LIL","Lille");
insert into city(ID, abbr, name) values (370,"LIM","Lima");
insert into city(ID, abbr, name) values (371,"LNZ","Linz");
insert into city(ID, abbr, name) values (372,"LIS","Lissabon");
insert into city(ID, abbr, name) values (373,"LIT","Little Rock");
insert into city(ID, abbr, name) values (374,"LJU","Ljubljana");
insert into city(ID, abbr, name) values (375,"LCY","London City");
insert into city(ID, abbr, name) values (376,"LGW","London-Gatwick");
insert into city(ID, abbr, name) values (377,"LHR","London-Heathrow");
insert into city(ID, abbr, name) values (378,"LON","London");
insert into city(ID, abbr, name) values (379,"LTN","London-Luton");
insert into city(ID, abbr, name) values (380,"STN","London-Stansted");
insert into city(ID, abbr, name) values (381,"LAX","Los Angeles");
insert into city(ID, abbr, name) values (382,"LRQ","Los Roques");
insert into city(ID, abbr, name) values (383,"SDF","Louisville");
insert into city(ID, abbr, name) values (384,"LDE","Lourdes");
insert into city(ID, abbr, name) values (385,"LBC","L\u00FCbeck-Blankensee");
insert into city(ID, abbr, name) values (386,"LUG","Lugano");
insert into city(ID, abbr, name) values (387,"LUX","Luxemburg");
insert into city(ID, abbr, name) values (388,"LXR","Luxor");
insert into city(ID, abbr, name) values (389,"LYS","Lyon");
insert into city(ID, abbr, name) values (390,"MST","Maastrich");
insert into city(ID, abbr, name) values (391,"MCZ","Maceio");
insert into city(ID, abbr, name) values (392,"MAD","Madrid");
insert into city(ID, abbr, name) values (393,"SEZ","Mahe");
insert into city(ID, abbr, name) values (394,"MAH","Mahon");
insert into city(ID, abbr, name) values (395,"LIN","Mailand-Linate");
insert into city(ID, abbr, name) values (396,"MPX","Mailand-Malpensa");
insert into city(ID, abbr, name) values (397,"MXP","Mailand-Malpensa");
insert into city(ID, abbr, name) values (398,"MIL","Mailand");
insert into city(ID, abbr, name) values (399,"AGP","Malaga");
insert into city(ID, abbr, name) values (400,"AGL","Malaga Linie");
insert into city(ID, abbr, name) values (401,"MZL","Malaga(Linie)");
insert into city(ID, abbr, name) values (402,"MLE","Male");
insert into city(ID, abbr, name) values (403,"HMA","Malmo");
insert into city(ID, abbr, name) values (404,"MMX","Malmo-Sturup");
insert into city(ID, abbr, name) values (405,"MDC","Manado");
insert into city(ID, abbr, name) values (406,"MGA","Managua");
insert into city(ID, abbr, name) values (407,"MAN","Manchester");
insert into city(ID, abbr, name) values (408,"MHT","Manchester");
insert into city(ID, abbr, name) values (409,"XMH","Manihi");
insert into city(ID, abbr, name) values (410,"MNL","Manila");
insert into city(ID, abbr, name) values (411,"ZLO","Manzanilo");
insert into city(ID, abbr, name) values (412,"GBJ","Marie Galante");
insert into city(ID, abbr, name) values (413,"RAK","Marrakesch");
insert into city(ID, abbr, name) values (414,"RMF","Marsa Alam 02");
insert into city(ID, abbr, name) values (415,"MSL","Marsa Alam");
insert into city(ID, abbr, name) values (416,"XXM","Marsa Alam Nec");
insert into city(ID, abbr, name) values (417,"MRS","Marseille");
insert into city(ID, abbr, name) values (418,"MHH","Marsh Harbour");
insert into city(ID, abbr, name) values (419,"AMI","Mataram");
insert into city(ID, abbr, name) values (420,"OGG","Maui");
insert into city(ID, abbr, name) values (421,"MUB","Maun");
insert into city(ID, abbr, name) values (422,"MRU","Mauritius");
insert into city(ID, abbr, name) values (423,"MES","Medan");
insert into city(ID, abbr, name) values (424,"MEL","Melbourne");
insert into city(ID, abbr, name) values (425,"MEM","Memphis");
insert into city(ID, abbr, name) values (426,"ETZ","Metz");
insert into city(ID, abbr, name) values (427,"MEX","Mexico City");
insert into city(ID, abbr, name) values (428,"MIA","Miami");
insert into city(ID, abbr, name) values (429,"ROR","Mikronesien");
insert into city(ID, abbr, name) values (430,"MKE","Milwaukee");
insert into city(ID, abbr, name) values (431,"MSP","Minneapolis/St. Paul");
insert into city(ID, abbr, name) values (432,"MSQ","Minsk");
insert into city(ID, abbr, name) values (433,"MPK","Mokpo");
insert into city(ID, abbr, name) values (434,"MKK","Molokai");
insert into city(ID, abbr, name) values (435,"MBA","Mombasa");
insert into city(ID, abbr, name) values (436,"MIR","Monastir");
insert into city(ID, abbr, name) values (437,"MGL","M\u00F6nchengladbach");
insert into city(ID, abbr, name) values (438,"YQM","Moncton");
insert into city(ID, abbr, name) values (439,"MBJ","Montego Bay");
insert into city(ID, abbr, name) values (440,"MVD","Montevideo");
insert into city(ID, abbr, name) values (441,"MPV","Montpelier");
insert into city(ID, abbr, name) values (442,"MPL","Montpellier");
insert into city(ID, abbr, name) values (443,"YMQ","Montreal");
insert into city(ID, abbr, name) values (444,"YMX","Montreal/YMX");
insert into city(ID, abbr, name) values (445,"MNI","Montserrat");
insert into city(ID, abbr, name) values (446,"MOZ","Moorea");
insert into city(ID, abbr, name) values (447,"HAH","Moroni");
insert into city(ID, abbr, name) values (448,"YVA","Moroni (YVA)");
insert into city(ID, abbr, name) values (449,"DME","Moskau-Domodedovo");
insert into city(ID, abbr, name) values (450,"MOW","Moskau");
insert into city(ID, abbr, name) values (451,"SVO","Moskau-Sheremetyevo");
insert into city(ID, abbr, name) values (452,"MLH","Mulhouse");
insert into city(ID, abbr, name) values (453,"MUC","M\u00FCnchen");
insert into city(ID, abbr, name) values (454,"FMO","M\u00FCnster-Osnabr\u00FCck");
insert into city(ID, abbr, name) values (455,"MJV","Murcia");
insert into city(ID, abbr, name) values (456,"MCT","Muscat");
insert into city(ID, abbr, name) values (457,"MQS","Mustique");
insert into city(ID, abbr, name) values (458,"JMK","Mykonos");
insert into city(ID, abbr, name) values (459,"NUE","N\u00FCrnberg");
insert into city(ID, abbr, name) values (460,"NAN","Nadi");
insert into city(ID, abbr, name) values (461,"NBO","Nairobi");
insert into city(ID, abbr, name) values (462,"NTE","Nantes");
insert into city(ID, abbr, name) values (463,"UAK","Narsarsuaq");
insert into city(ID, abbr, name) values (464,"BNA","Nashville");
insert into city(ID, abbr, name) values (465,"NAS","Nassau");
insert into city(ID, abbr, name) values (466,"NAT","Natal");
insert into city(ID, abbr, name) values (467,"JNX","Naxos");
insert into city(ID, abbr, name) values (468,"NAP","Neapel");
insert into city(ID, abbr, name) values (469,"FNB","Neubrandenburg");
insert into city(ID, abbr, name) values (470,"ZUB","Neubrandenburg");
insert into city(ID, abbr, name) values (471,"NEV","Nevis");
insert into city(ID, abbr, name) values (472,"HVN","New Haven");
insert into city(ID, abbr, name) values (473,"MSY","New Orleans");
insert into city(ID, abbr, name) values (474,"NPT","Newport");
insert into city(ID, abbr, name) values (475,"JFK","New York (JFK)");
insert into city(ID, abbr, name) values (476,"EWR","New York (Newark)");
insert into city(ID, abbr, name) values (477,"NYC","New York");
insert into city(ID, abbr, name) values (478,"NHA","Nha Trang");
insert into city(ID, abbr, name) values (479,"FNI","Nimes");
insert into city(ID, abbr, name) values (480,"NCE","Nizza");
insert into city(ID, abbr, name) values (481,"ORF","Norfolk");
insert into city(ID, abbr, name) values (482,"NOS","Nosy Be");
insert into city(ID, abbr, name) values (483,"NOU","Noumea");
insert into city(ID, abbr, name) values (484,"TBU","Nuku\u0180Alova");
insert into city(ID, abbr, name) values (485,"ODS","Odessa");
insert into city(ID, abbr, name) values (486,"OKC","Oklahoma City");
insert into city(ID, abbr, name) values (487,"OLB","Olbia");
insert into city(ID, abbr, name) values (488,"MCO","Orlando");
insert into city(ID, abbr, name) values (489,"ITM","Osaka / ITM");
insert into city(ID, abbr, name) values (490,"KIX","Osaka / KIX");
insert into city(ID, abbr, name) values (491,"OSA","Osaka");
insert into city(ID, abbr, name) values (492,"FBU","Oslo");
insert into city(ID, abbr, name) values (493,"OSL","Oslo/OSL");
insert into city(ID, abbr, name) values (494,"TRF","Oslo Torp");
insert into city(ID, abbr, name) values (495,"YOW","Ottawa");
insert into city(ID, abbr, name) values (496,"OZZ","Ouarzazate");
insert into city(ID, abbr, name) values (497,"OUL","Oulu");
insert into city(ID, abbr, name) values (498,"OVD","Oviedo");
insert into city(ID, abbr, name) values (499,"PDG","Padang");
insert into city(ID, abbr, name) values (500,"PAD","Paderborn-Lippstadt");
insert into city(ID, abbr, name) values (501,"PLQ","Palanga");
insert into city(ID, abbr, name) values (502,"PMO","Palermo");
insert into city(ID, abbr, name) values (503,"PMI","Palma de Mallorca");
insert into city(ID, abbr, name) values (504,"PML","Palma Linie");
insert into city(ID, abbr, name) values (505,"PBI","Palm Beach");
insert into city(ID, abbr, name) values (506,"PSP","Palm Springs");
insert into city(ID, abbr, name) values (507,"UNI","Palm/Union Island");
insert into city(ID, abbr, name) values (508,"PTY","Panama City");
insert into city(ID, abbr, name) values (509,"PKG","Pangkor");
insert into city(ID, abbr, name) values (510,"PNL","Pantelleria");
insert into city(ID, abbr, name) values (511,"PFO","Paphos");
insert into city(ID, abbr, name) values (512,"PID","Paradise Island");
insert into city(ID, abbr, name) values (513,"CDG","Paris_Charles-de-Gaulle");
insert into city(ID, abbr, name) values (514,"ORY","Paris_Orly");
insert into city(ID, abbr, name) values (515,"PAR","Paris");
insert into city(ID, abbr, name) values (516,"PAS","Paros");
insert into city(ID, abbr, name) values (517,"BJS","Peking");
insert into city(ID, abbr, name) values (518,"PEK","Peking (PEK)");
insert into city(ID, abbr, name) values (519,"PEN","Penang");
insert into city(ID, abbr, name) values (520,"NPA","Pensacola");
insert into city(ID, abbr, name) values (521,"PGF","Perpignan");
insert into city(ID, abbr, name) values (522,"PER","Perth");
insert into city(ID, abbr, name) values (523,"PEG","Perugia");
insert into city(ID, abbr, name) values (524,"PSR","Pescara");
insert into city(ID, abbr, name) values (525,"PHL","Philadelphi");
insert into city(ID, abbr, name) values (526,"PHX","Phoenix");
insert into city(ID, abbr, name) values (527,"HKT","Phuket");
insert into city(ID, abbr, name) values (528,"PIX","Pico Island");
insert into city(ID, abbr, name) values (529,"PSA","Pisa");
insert into city(ID, abbr, name) values (530,"PIT","Pittsburgh");
insert into city(ID, abbr, name) values (531,"PLJ","Placencia");
insert into city(ID, abbr, name) values (532,"PDV","Plovdiv");
insert into city(ID, abbr, name) values (533,"PNH","Pnom Penh");
insert into city(ID, abbr, name) values (534,"KPO","Pohang");
insert into city(ID, abbr, name) values (535,"PTP","Pointe a Pitre");
insert into city(ID, abbr, name) values (536,"PMV","Polarmar");
insert into city(ID, abbr, name) values (537,"PDL","Ponta Delgada");
insert into city(ID, abbr, name) values (538,"PAP","Port au Prince");
insert into city(ID, abbr, name) values (539,"PLZ","Port Elizabeth");
insert into city(ID, abbr, name) values (540,"PDX","Portland");
insert into city(ID, abbr, name) values (541,"PWM","Portland");
insert into city(ID, abbr, name) values (542,"POM","Port Moresby");
insert into city(ID, abbr, name) values (543,"POS","Port of Spain");
insert into city(ID, abbr, name) values (544,"OPO","Porto");
insert into city(ID, abbr, name) values (545,"PXO","Porto Santo");
insert into city(ID, abbr, name) values (546,"BPS","Porto Seguro");
insert into city(ID, abbr, name) values (547,"POZ","Posen");
insert into city(ID, abbr, name) values (548,"PRG","Prag");
insert into city(ID, abbr, name) values (549,"PRI","Praslin");
insert into city(ID, abbr, name) values (550,"PVK","Preveza");
insert into city(ID, abbr, name) values (551,"PVD","Providence");
insert into city(ID, abbr, name) values (552,"PLS","Providenciales");
insert into city(ID, abbr, name) values (553,"PVA","Providencia");
insert into city(ID, abbr, name) values (554,"PXM","Puerto Escondido");
insert into city(ID, abbr, name) values (555,"POP","Puerto Plata");
insert into city(ID, abbr, name) values (556,"PVR","Puerto Vallarta");
insert into city(ID, abbr, name) values (557,"PUY","Pula");
insert into city(ID, abbr, name) values (558,"PUJ","Punta Cana");
insert into city(ID, abbr, name) values (559,"YQB","Quebec");
insert into city(ID, abbr, name) values (560,"QIP","Quimper");
insert into city(ID, abbr, name) values (561,"UIO","Quito");
insert into city(ID, abbr, name) values (562,"RUN","Reunion");
insert into city(ID, abbr, name) values (563,"RDU","Raleigh/Durham");
insert into city(ID, abbr, name) values (564,"RGI","Rangiroa");
insert into city(ID, abbr, name) values (565,"RAP","Rapid City");
insert into city(ID, abbr, name) values (566,"REC","Recife");
insert into city(ID, abbr, name) values (567,"REG","Reggio Calabria");
insert into city(ID, abbr, name) values (568,"TFS","Reina Sofia");
insert into city(ID, abbr, name) values (569,"RNO","Reno");
insert into city(ID, abbr, name) values (570,"REU","Reus");
insert into city(ID, abbr, name) values (571,"KEF","Reykjavik");
insert into city(ID, abbr, name) values (572,"RHO","Rhodos");
insert into city(ID, abbr, name) values (573,"RIC","Richmond");
insert into city(ID, abbr, name) values (574,"RIX","Riga");
insert into city(ID, abbr, name) values (575,"RJK","Rijeka");
insert into city(ID, abbr, name) values (576,"RMI","Rimini");
insert into city(ID, abbr, name) values (577,"GIG","Rio GIG");
insert into city(ID, abbr, name) values (578,"RIO","Rio");
insert into city(ID, abbr, name) values (579,"CIA","Rom Ciampino");
insert into city(ID, abbr, name) values (580,"FCO","Rom (FCO)");
insert into city(ID, abbr, name) values (581,"ROM","Rom");
insert into city(ID, abbr, name) values (582,"RNN","Ronne");
insert into city(ID, abbr, name) values (583,"RLG","Rostock");
insert into city(ID, abbr, name) values (584,"RTM","Rotterdam");
insert into city(ID, abbr, name) values (585,"RVN","Rovaniemi");
insert into city(ID, abbr, name) values (586,"SCN","Saarbr\u00FCcken");
insert into city(ID, abbr, name) values (587,"SOB","Saarmellek");
insert into city(ID, abbr, name) values (588,"SAB","Saba");
insert into city(ID, abbr, name) values (589,"SAW","Sabiha Gokcen");
insert into city(ID, abbr, name) values (590,"SGN","Saigon");
insert into city(ID, abbr, name) values (591,"SLL","Salalah");
insert into city(ID, abbr, name) values (592,"SID","Sal");
insert into city(ID, abbr, name) values (593,"SLC","Salt Lake City");
insert into city(ID, abbr, name) values (594,"SSA","Salvador de Bahia");
insert into city(ID, abbr, name) values (595,"SZG","Salzburg");
insert into city(ID, abbr, name) values (596,"SRI","Samarinda");
insert into city(ID, abbr, name) values (597,"SMI","Samos");
insert into city(ID, abbr, name) values (598,"SSX","Samsun");
insert into city(ID, abbr, name) values (599,"SZF","Samsun");
insert into city(ID, abbr, name) values (600,"ADZ","San Andres");
insert into city(ID, abbr, name) values (601,"SAT","San Antonio");
insert into city(ID, abbr, name) values (602,"SAH","San'a");
insert into city(ID, abbr, name) values (603,"SDK","Sandakan");
insert into city(ID, abbr, name) values (604,"SAN","San Diego");
insert into city(ID, abbr, name) values (605,"SFB","Sanford");
insert into city(ID, abbr, name) values (606,"SFO","San Francisco");
insert into city(ID, abbr, name) values (607,"SJD","San Jose del Cabo");
insert into city(ID, abbr, name) values (608,"SJO","San Jose");
insert into city(ID, abbr, name) values (609,"SJU","San Juan");
insert into city(ID, abbr, name) values (610,"SPR","San Pedro");
insert into city(ID, abbr, name) values (611,"SAP","San Pedro Sula");
insert into city(ID, abbr, name) values (612,"SAL","San Salvador");
insert into city(ID, abbr, name) values (613,"ZSA","San Salvador");
insert into city(ID, abbr, name) values (614,"SFN","Santa Fe");
insert into city(ID, abbr, name) values (615,"SCL","Santiago de Chile");
insert into city(ID, abbr, name) values (616,"SCQ","Santiago de Composte");
insert into city(ID, abbr, name) values (617,"SCU","Santiago de Cuba");
insert into city(ID, abbr, name) values (618,"RAI","Santiago");
insert into city(ID, abbr, name) values (619,"SDQ","Santo Domingo");
insert into city(ID, abbr, name) values (620,"JTR","Santorin");
insert into city(ID, abbr, name) values (621,"SYX","Sanya");
insert into city(ID, abbr, name) values (622,"SAO","Sao Paulo");
insert into city(ID, abbr, name) values (623,"SJJ","Sarajevo");
insert into city(ID, abbr, name) values (624,"SRQ","Sarasota");
insert into city(ID, abbr, name) values (625,"YXE","Saskatoon");
insert into city(ID, abbr, name) values (626,"SAV","Savannah");
insert into city(ID, abbr, name) values (627,"SZW","Schwerin");
insert into city(ID, abbr, name) values (628,"ZSR","Schwerin");
insert into city(ID, abbr, name) values (629,"SEA","Seattle");
insert into city(ID, abbr, name) values (630,"SEL","Seoul");
insert into city(ID, abbr, name) values (631,"SVQ","Sevilla");
insert into city(ID, abbr, name) values (632,"SHA","Shanghai");
insert into city(ID, abbr, name) values (633,"SNN","Shannon");
insert into city(ID, abbr, name) values (634,"SHJ","Sharjah");
insert into city(ID, abbr, name) values (635,"SSH","Sharm El Sheikh");
insert into city(ID, abbr, name) values (636,"REP","Siam Reap");
insert into city(ID, abbr, name) values (637,"SBZ","Sibiu (Hermannstadt)");
insert into city(ID, abbr, name) values (638,"SIP","Simferopol");
insert into city(ID, abbr, name) values (639,"SIN","Singapur");
insert into city(ID, abbr, name) values (640,"JSI","Skiathos");
insert into city(ID, abbr, name) values (641,"SKP","Skopje");
insert into city(ID, abbr, name) values (642,"SXL","Sligo");
insert into city(ID, abbr, name) values (643,"SOF","Sofia");
insert into city(ID, abbr, name) values (644,"AER","Sotschi");
insert into city(ID, abbr, name) values (645,"SPU","Split");
insert into city(ID, abbr, name) values (646,"SMR","Sta. Marta");
insert into city(ID, abbr, name) values (647,"SVG","Stavanger");
insert into city(ID, abbr, name) values (648,"SBH","St. Barthelemy");
insert into city(ID, abbr, name) values (649,"STX","St. Croix");
insert into city(ID, abbr, name) values (650,"SML","Stella Maris");
insert into city(ID, abbr, name) values (651,"EUX","St. Eustatius");
insert into city(ID, abbr, name) values (652,"ACH","St. Gallen/Altenrhein");
insert into city(ID, abbr, name) values (653,"SJF","St. John");
insert into city(ID, abbr, name) values (654,"SKB","St. Kitts");
insert into city(ID, abbr, name) values (655,"UVF","St. Lucia");
insert into city(ID, abbr, name) values (656,"SLU","St Lucia Vigie");
insert into city(ID, abbr, name) values (657,"SXM","St. Maarten");
insert into city(ID, abbr, name) values (658,"MSB","St Martin");
insert into city(ID, abbr, name) values (659,"ARN","Stockholm Arlanda");
insert into city(ID, abbr, name) values (660,"BMA","Stockholm Bromma");
insert into city(ID, abbr, name) values (661,"NYO","Stockholm S. Skavsta");
insert into city(ID, abbr, name) values (662,"STO","Stockholm");
insert into city(ID, abbr, name) values (663,"LED","St. Petersburg");
insert into city(ID, abbr, name) values (664,"SXB","Strasbourg");
insert into city(ID, abbr, name) values (665,"STT","St. Thomas");
insert into city(ID, abbr, name) values (666,"STR","Stuttgart");
insert into city(ID, abbr, name) values (667,"SVD","St. Vincent");
insert into city(ID, abbr, name) values (668,"SYD","Sydney");
insert into city(ID, abbr, name) values (669,"SZY","Szczytno/Ortelsburg");
insert into city(ID, abbr, name) values (670,"TBJ","Tabarka");
insert into city(ID, abbr, name) values (671,"TCP","Taba");
insert into city(ID, abbr, name) values (672,"PPT","Tahiti");
insert into city(ID, abbr, name) values (673,"TPE","Taipei");
insert into city(ID, abbr, name) values (674,"TLL","Tallin");
insert into city(ID, abbr, name) values (675,"TPA","Tampa");
insert into city(ID, abbr, name) values (676,"TNG","Tanger");
insert into city(ID, abbr, name) values (677,"TRK","Tarakan");
insert into city(ID, abbr, name) values (678,"TWU","Tawau");
insert into city(ID, abbr, name) values (679,"TBS","Tbilisi");
insert into city(ID, abbr, name) values (680,"THR","Teheran");
insert into city(ID, abbr, name) values (681,"TLV","Tel Aviv");
insert into city(ID, abbr, name) values (682,"TEX","Telluride");
insert into city(ID, abbr, name) values (683,"TCI","Teneriffa-Nord");
insert into city(ID, abbr, name) values (684,"TFN","Teneriffa Nord");
insert into city(ID, abbr, name) values (685,"TER","Terceira");
insert into city(ID, abbr, name) values (686,"TGG","Terengganu");
insert into city(ID, abbr, name) values (687,"TTU","Tetouan");
insert into city(ID, abbr, name) values (688,"SKG","Thessaloniki");
insert into city(ID, abbr, name) values (689,"TSR","Timisoara");
insert into city(ID, abbr, name) values (690,"TOD","Tioman");
insert into city(ID, abbr, name) values (691,"TIV","Tivat");
insert into city(ID, abbr, name) values (692,"TAB","Tobago");
insert into city(ID, abbr, name) values (693,"TYO","Tokio");
insert into city(ID, abbr, name) values (694,"YYZ","Toronto");
insert into city(ID, abbr, name) values (695,"TTB","Tortoli");
insert into city(ID, abbr, name) values (696,"EIS","Totola-Beef Island");
insert into city(ID, abbr, name) values (697,"TLN","Toulon");
insert into city(ID, abbr, name) values (698,"TSV","Townsville");
insert into city(ID, abbr, name) values (699,"TOE","Tozeur");
insert into city(ID, abbr, name) values (700,"TZX","Trabzon");
insert into city(ID, abbr, name) values (701,"TPS","Trapani");
insert into city(ID, abbr, name) values (702,"TSF","Treviso");
insert into city(ID, abbr, name) values (703,"TRS","Triest");
insert into city(ID, abbr, name) values (704,"TRV","Trivandarum");
insert into city(ID, abbr, name) values (705,"TOS","Tromso");
insert into city(ID, abbr, name) values (706,"TUS","Tucson");
insert into city(ID, abbr, name) values (707,"TNZ","Tunis(Linie)");
insert into city(ID, abbr, name) values (708,"TUN","Tunis");
insert into city(ID, abbr, name) values (709,"TRN","Turin");
insert into city(ID, abbr, name) values (710,"TKU","Turku");
insert into city(ID, abbr, name) values (711,"UPG","Ujung Padang");
insert into city(ID, abbr, name) values (712,"ULN","Ulan Bator");
insert into city(ID, abbr, name) values (713,"UTP","Utapao");
insert into city(ID, abbr, name) values (714,"FAE","Vagar");
insert into city(ID, abbr, name) values (715,"VLC","Valencia");
insert into city(ID, abbr, name) values (716,"VDE","Valverde");
insert into city(ID, abbr, name) values (717,"YVR","Vancouver");
insert into city(ID, abbr, name) values (718,"VRA","Varadero");
insert into city(ID, abbr, name) values (719,"VAR","Varna");
insert into city(ID, abbr, name) values (720,"VCE","Venedig");
insert into city(ID, abbr, name) values (721,"VER","Veracruz");
insert into city(ID, abbr, name) values (722,"VRN","Verona");
insert into city(ID, abbr, name) values (723,"VFA","Victoria Falls");
insert into city(ID, abbr, name) values (724,"VTE","Vientiane");
insert into city(ID, abbr, name) values (725,"VQS","Vieques");
insert into city(ID, abbr, name) values (726,"VGO","Vigo");
insert into city(ID, abbr, name) values (727,"VNO","Vilnius");
insert into city(ID, abbr, name) values (728,"VIJ","Virgin Gorda");
insert into city(ID, abbr, name) values (729,"WAW","Warschau");
insert into city(ID, abbr, name) values (730,"DCA","Washington/DCA");
insert into city(ID, abbr, name) values (731,"IAD","Washington International");
insert into city(ID, abbr, name) values (732,"WAS","Washington-WAS");
insert into city(ID, abbr, name) values (733,"WLG","Wellington");
insert into city(ID, abbr, name) values (734,"YXY","Whitehorse");
insert into city(ID, abbr, name) values (735,"VIE","Wien");
insert into city(ID, abbr, name) values (736,"WDH","Windhoek");
insert into city(ID, abbr, name) values (737,"YWG","Winnipeg");
insert into city(ID, abbr, name) values (738,"SIA","Xian");
insert into city(ID, abbr, name) values (739,"RGN","Yangoon / Rangoon");
insert into city(ID, abbr, name) values (740,"YAP","Yap");
insert into city(ID, abbr, name) values (741,"YZF","Yellowknife");
insert into city(ID, abbr, name) values (742,"JOG","Yogyakarta");
insert into city(ID, abbr, name) values (743,"ZAD","Zadar");
insert into city(ID, abbr, name) values (744,"ZAG","Zagreb");
insert into city(ID, abbr, name) values (745,"ZTH","Zakynthos");
insert into city(ID, abbr, name) values (746,"ZNZ","Zanzibar");
insert into city(ID, abbr, name) values (747,"ZIH","Zihuatanejo");
insert into city(ID, abbr, name) values (748,"ZRH","Z\u00FCrich");
insert into city(ID, abbr, name) values (749,"ZQW","Zweibr\u00FCcken");
