#
# Table structure for table 'country'
#

DROP TABLE country;

CREATE TABLE  country (
	ID bigint NOT NULL,
	abbr2 varchar(2),
	abbr3 varchar(3),
	name varchar(100),
PRIMARY KEY (ID) 
);

INSERT INTO country (ID,abbr2,abbr3,name) VALUES (1,'PE','PER','Peru');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (2,'QA','QAT','Qatar');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (3,'LA','LAO','Lao Peoples Democratic Republic');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (4,'KE','KEN','Kenya');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (5,'MN','MNG','Mongolia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (6,'CF','CAF','Central African Republic');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (7,'SM','SMR','San Marino');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (8,'DE','DEU','Germany');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (9,'SR','SUR','Suriname');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (10,'TV','TUV','Tuvalu');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (11,'DZ','DZA','Algeria');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (12,'CK','COK','Cook Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (13,'YE','YEM','Yemen');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (14,'ZM','ZMB','Zambia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (15,'NG','NGA','Nigeria');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (16,'BW','BWA','Botswana');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (17,'SI','SVN','Slovenia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (18,'HT','HTI','Haiti');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (19,'SN','SEN','Senegal');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (20,'--','---','Anonymous');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (21,'CD','COD','Congo The Democratic Republic Of The');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (22,'MT','MLT','Malta');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (23,'==','===','Not found');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (24,'GB','GBR','United Kingdom');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (25,'WS','WSM','Samoa');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (26,'++','+++','Reserved');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (27,'LC','LCA','Saint Lucia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (28,'FI','FIN','Finland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (29,'HU','HUN','Hungary');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (30,'KG','KGZ','Kyrgyzstan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (31,'JM','JAM','Jamaica');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (32,'MR','MRT','Mauritania');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (33,'JO','JOR','Jordan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (34,'SV','SLV','El Salvador');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (35,'EC','ECU','Ecuador');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (36,'MP','MNP','Northern Mariana Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (37,'GE','GEO','Georgia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (38,'MK','MKD','Macedonia The Former Yugoslav Republic Of');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (39,'OM','OMN','Oman');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (40,'CS','CS','Serbia And Montenegro (formally Czechoslovakia)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (41,'GF','GUF','French Guiana');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (42,'LB','LBN','Lebanon');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (43,'MU','MUS','Mauritius');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (44,'SL','SLE','Sierra Leone');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (45,'SA','SAU','Saudi Arabia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (46,'US','USA','United States');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (47,'MO','MAC','Macau');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (48,'GD','GRD','Grenada');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (49,'GA','GAB','Gabon');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (50,'BA','BIH','Bosnia And Herzegowina');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (51,'KZ','KAZ','Kazakhstan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (52,'CH','CHE','Switzerland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (53,'SY','SYR','Syrian Arab Republic');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (54,'BB','BRB','Barbados');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (55,'KY','CYM','Cayman Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (56,'GL','GRL','Greenland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (57,'RO','ROM','Romania');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (58,'AD','AND','Andorra');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (59,'IL','ISR','Israel');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (60,'CN','CHN','China');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (61,'SK','SVK','Slovakia (slovak Republic)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (62,'NL','NLD','Netherlands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (63,'VI','VIR','Virgin Islands (u.s.)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (64,'BY','BLR','Belarus');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (65,'IO','IOT','British Indian Ocean Territory');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (66,'UA','UKR','Ukraine');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (67,'AG','ATG','Antigua And Barbuda');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (68,'GM','GMB','Gambia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (69,'AE','ARE','United Arab Emirates');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (70,'PL','POL','Poland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (71,'EE','EST','Estonia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (72,'CL','CHL','Chile');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (73,'SD','SDN','Sudan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (74,'MV','MDV','Maldives');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (75,'NA','NAM','Namibia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (76,'CM','CMR','Cameroon');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (77,'PK','PAK','Pakistan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (78,'BZ','BLZ','Belize');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (79,'SG','SGP','Singapore');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (80,'ID','IDN','Indonesia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (81,'PS','PSE','Palestinian Territory Occupied');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (82,'NC','NCL','New Caledonia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (83,'BT','BTN','Bhutan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (84,'GY','GUY','Guyana');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (85,'DO','DOM','Dominican Republic');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (86,'KR','KOR','Korea Republic Of');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (87,'CO','COL','Colombia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (88,'BS','BHS','Bahamas');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (89,'FR','FRA','France');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (90,'HR','HRV','Croatia (local Name: Hrvatska)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (91,'SE','SWE','Sweden');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (92,'MW','MWI','Malawi');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (93,'NE','NER','Niger');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (94,'AF','AFG','Afghanistan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (95,'PG','PNG','Papua New Guinea');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (96,'IE','IRL','Ireland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (97,'SZ','SWZ','Swaziland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (98,'CI','CIV','Cote Divoire');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (99,'HK','HKG','Hong Kong');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (100,'AZ','AZE','Azerbaijan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (101,'PH','PHL','Philippines');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (102,'NF','NFK','Norfolk Island');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (103,'PR','PRI','Puerto Rico');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (104,'IN','IND','India');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (105,'ZA','ZAF','South Africa');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (106,'AI','AIA','Anguilla');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (107,'TT','TTO','Trinidad And Tobago');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (108,'PA','PAN','Panama');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (109,'KH','KHM','Cambodia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (110,'PT','PRT','Portugal');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (111,'PF','PYF','French Polynesia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (112,'KI','KIR','Kiribati');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (113,'IQ','IRQ','Iraq');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (114,'FO','FRO','Faroe Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (115,'VG','VGB','Virgin Islands (british)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (116,'NI','NIC','Nicaragua');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (117,'VN','VNM','Viet Nam');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (118,'ET','ETH','Ethiopia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (119,'AP','AFR','Non-spec Asia Pas Location');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (120,'LK','LKA','Sri Lanka');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (121,'AS','ASM','American Samoa');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (122,'ER','ERI','Eritrea');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (123,'MZ','MOZ','Mozambique');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (124,'AN','ANT','Netherlands Antilles');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (125,'KN','KNA','Saint Kitts And Nevis');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (126,'VE','VEN','Venezuela');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (127,'TR','TUR','Turkey');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (128,'BD','BGD','Bangladesh');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (129,'TO','TON','Tonga');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (130,'BJ','BEN','Benin');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (131,'GR','GRC','Greece');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (132,'EU','EU','European Union');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (133,'MC','MCO','Monaco');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (134,'TJ','TJK','Tajikistan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (135,'BF','BFA','Burkina Faso');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (136,'TM','TKM','Turkmenistan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (137,'AU','AUS','Australia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (138,'UY','URY','Uruguay');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (139,'IR','IRN','Iran (islamic Republic Of)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (140,'TN','TUN','Tunisia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (141,'AT','AUT','Austria');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (142,'CZ','CZE','Czech Republic');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (143,'GH','GHA','Ghana');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (144,'MG','MDG','Madagascar');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (145,'AM','ARM','Armenia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (146,'UZ','UZB','Uzbekistan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (147,'LT','LTU','Lithuania');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (148,'BE','BEL','Belgium');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (149,'AX','ALA','åland Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (150,'RU','RUS','Russian Federation');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (151,'MY','MYS','Malaysia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (152,'BG','BGR','Bulgaria');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (153,'AO','AGO','Angola');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (154,'AL','ALB','Albania');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (155,'AW','ABW','Aruba');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (156,'MX','MEX','Mexico');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (157,'IT','ITA','Italy');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (158,'BR','BRA','Brazil');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (159,'RW','RWA','Rwanda');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (160,'BI','BDI','Burundi');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (161,'CY','CYP','Cyprus');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (162,'GI','GIB','Gibraltar');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (163,'EG','EGY','Egypt');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (164,'SC','SYC','Seychelles');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (165,'VA','VAT','Holy See (vatican City State)');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (166,'CR','CRI','Costa Rica');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (167,'VU','VUT','Vanuatu');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (168,'UG','UGA','Uganda');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (169,'BO','BOL','Bolivia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (170,'ZW','ZWE','Zimbabwe');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (171,'NP','NPL','Nepal');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (172,'GU','GUM','Guam');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (173,'SB','SLB','Solomon Islands');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (174,'TH','THA','Thailand');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (175,'MA','MAR','Morocco');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (176,'ML','MLI','Mali');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (177,'LR','LBR','Liberia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (178,'JP','JPN','Japan');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (179,'DK','DNK','Denmark');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (180,'HN','HND','Honduras');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (181,'NR','NRU','Nauru');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (182,'LS','LSO','Lesotho');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (183,'FJ','FJI','Fiji');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (184,'DJ','DJI','Djibouti');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (185,'TZ','TZA','Tanzania United Republic Of');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (186,'MM','MMR','Myanmar');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (187,'BH','BHR','Bahrain');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (188,'BM','BMU','Bermuda');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (189,'CU','CUB','Cuba');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (190,'LI','LIE','Liechtenstein');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (191,'PY','PRY','Paraguay');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (192,'PW','PLW','Palau');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (193,'BN','BRN','Brunei Darussalam');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (194,'IS','ISL','Iceland');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (195,'LV','LVA','Latvia');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (196,'NO','NOR','Norway');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (197,'GT','GTM','Guatemala');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (198,'MD','MDA','Moldova Republic Of');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (199,'LY','LBY','Libyan Arab Jamahiriya');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (200,'ES','ESP','Spain');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (201,'TW','TWN','Taiwan Province Of China');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (202,'KW','KWT','Kuwait');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (203,'CA','CAN','Canada');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (204,'TG','TGO','Togo');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (205,'FM','FSM','Micronesia Federated States Of');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (206,'NU','NIU','Niue');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (207,'GW','GNB','Guinea-bissau');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (208,'AR','ARG','Argentina');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (209,'LU','LUX','Luxembourg');
INSERT INTO country (ID,abbr2,abbr3,name) VALUES (210,'NZ','NZL','New Zealand');