DROP TABLE  systemsettings;
CREATE TABLE   systemsettings (
  ID  bigint NOT NULL ,
  SSVALUE varchar (200),
  SSKEY varchar (200),
  TYPEID INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE(SSKEY)
);

INSERT INTO systemsettings VALUES(0, 'unidentified language', 'unidentified language', 0);
INSERT INTO systemsettings VALUES(1, 'Afar', 'aa', 1);
INSERT INTO systemsettings VALUES(2, 'Abkhazian', 'ab', 1);
INSERT INTO systemsettings VALUES(3, 'Avestan', 'ae', 1);
INSERT INTO systemsettings VALUES(4, 'Afrikaans', 'af', 1);
INSERT INTO systemsettings VALUES(5, 'Akan', 'ak', 1);
INSERT INTO systemsettings VALUES(6, 'Amharic', 'am', 1);
INSERT INTO systemsettings VALUES(7, 'Aragonese', 'an', 1);
INSERT INTO systemsettings VALUES(8, 'Arabic', 'ar', 1);
INSERT INTO systemsettings VALUES(9, 'Assamese', 'as', 1);
INSERT INTO systemsettings VALUES(10, 'Asturian', 'ast', 1);
INSERT INTO systemsettings VALUES(11, 'Avaric', 'av', 1);
INSERT INTO systemsettings VALUES(12, 'Aymara', 'ay', 1);
INSERT INTO systemsettings VALUES(13, 'Azerbaijani', 'az', 1);
INSERT INTO systemsettings VALUES(14, 'Bashkir', 'ba', 1);
INSERT INTO systemsettings VALUES(15, 'Belarusian', 'be', 1);
INSERT INTO systemsettings VALUES(16, 'Bulgarian', 'bg', 1);
INSERT INTO systemsettings VALUES(17, 'Bihari', 'bh', 1);
INSERT INTO systemsettings VALUES(18, 'Bislama', 'bi', 1);
INSERT INTO systemsettings VALUES(19, 'Bambara', 'bm', 1);
INSERT INTO systemsettings VALUES(20, 'Bengali', 'bn', 1);
INSERT INTO systemsettings VALUES(21, 'Tibetan', 'bo', 1);
INSERT INTO systemsettings VALUES(22, 'Breton', 'br', 1);
INSERT INTO systemsettings VALUES(23, 'Bosnian', 'bs', 1);
INSERT INTO systemsettings VALUES(24, 'Catalan', 'ca', 1);
INSERT INTO systemsettings VALUES(25, 'Chechen', 'ce', 1);
INSERT INTO systemsettings VALUES(26, 'Chamorro', 'ch', 1);
INSERT INTO systemsettings VALUES(27, 'Corsican', 'co', 1);
INSERT INTO systemsettings VALUES(28, 'Cree', 'cr', 1);
INSERT INTO systemsettings VALUES(29, 'Czech', 'cs', 1);
INSERT INTO systemsettings VALUES(30, 'Church Slavic', 'cu', 1);
INSERT INTO systemsettings VALUES(31, 'Chuvash', 'cv', 1);
INSERT INTO systemsettings VALUES(32, 'Welsh', 'cy', 1);
INSERT INTO systemsettings VALUES(33, 'Danish', 'da', 1);
INSERT INTO systemsettings VALUES(34, 'German', 'de', 1);
INSERT INTO systemsettings VALUES(35, 'Divehi', 'dv', 1);
INSERT INTO systemsettings VALUES(36, 'Bhutani', 'dz', 1);
INSERT INTO systemsettings VALUES(37, 'Ewe', 'ee', 1);
INSERT INTO systemsettings VALUES(38, 'Greek', 'el', 1);
INSERT INTO systemsettings VALUES(39, 'English', 'en', 1);
INSERT INTO systemsettings VALUES(40, 'Esperanto', 'eo', 1);
INSERT INTO systemsettings VALUES(41, 'Spanish', 'es', 1);
INSERT INTO systemsettings VALUES(42, 'Estonian', 'et', 1);
INSERT INTO systemsettings VALUES(43, 'Basque', 'eu', 1);
INSERT INTO systemsettings VALUES(44, 'Persian', 'fa', 1);
INSERT INTO systemsettings VALUES(45, 'Fulah', 'ff', 1);
INSERT INTO systemsettings VALUES(46, 'Finnish', 'fi', 1);
INSERT INTO systemsettings VALUES(47, 'Fijian', 'fj', 1);
INSERT INTO systemsettings VALUES(48, 'Faeroese', 'fo', 1);
INSERT INTO systemsettings VALUES(49, 'French', 'fr', 1);
INSERT INTO systemsettings VALUES(50, 'Frisian', 'fy', 1);
INSERT INTO systemsettings VALUES(51, 'Irish', 'ga', 1);
INSERT INTO systemsettings VALUES(52, 'Scots Gaelic', 'gd', 1);
INSERT INTO systemsettings VALUES(53, 'Galician', 'gl', 1);
INSERT INTO systemsettings VALUES(54, 'Guarani', 'gn', 1);
INSERT INTO systemsettings VALUES(55, 'Gujarati', 'gu', 1);
INSERT INTO systemsettings VALUES(56, 'Manx', 'gv', 1);
INSERT INTO systemsettings VALUES(57, 'Hausa', 'ha', 1);
INSERT INTO systemsettings VALUES(58, 'Hebrew', 'he', 1);
INSERT INTO systemsettings VALUES(59, 'Hindi', 'hi', 1);
INSERT INTO systemsettings VALUES(60, 'Hiri Motu', 'ho', 1);
INSERT INTO systemsettings VALUES(61, 'Croatian', 'hr', 1);
INSERT INTO systemsettings VALUES(62, 'Upper Sorbian', 'hsb', 1);
INSERT INTO systemsettings VALUES(63, 'Haitian', 'ht', 1);
INSERT INTO systemsettings VALUES(64, 'Hungarian', 'hu', 1);
INSERT INTO systemsettings VALUES(65, 'Armenian', 'hy', 1);
INSERT INTO systemsettings VALUES(66, 'Herero', 'hz', 1);
INSERT INTO systemsettings VALUES(67, 'Interlingua', 'ia', 1);
INSERT INTO systemsettings VALUES(68, 'Indonesian', 'id', 1);
INSERT INTO systemsettings VALUES(69, 'Interlingue', 'ie', 1);
INSERT INTO systemsettings VALUES(70, 'Igbo', 'ig', 1);
INSERT INTO systemsettings VALUES(71, 'Sichuan Yi', 'ii', 1);
INSERT INTO systemsettings VALUES(72, 'Inupiak', 'ik', 1);
INSERT INTO systemsettings VALUES(73, 'Ido', 'io', 1);
INSERT INTO systemsettings VALUES(74, 'Icelandic', 'is', 1);
INSERT INTO systemsettings VALUES(75, 'Italian', 'it', 1);
INSERT INTO systemsettings VALUES(76, 'Inuktitut', 'iu', 1);
INSERT INTO systemsettings VALUES(77, 'Japanese', 'ja', 1);
INSERT INTO systemsettings VALUES(78, 'Javanese', 'jv', 1);
INSERT INTO systemsettings VALUES(79, 'Georgian', 'ka', 1);
INSERT INTO systemsettings VALUES(80, 'Kongo', 'kg', 1);
INSERT INTO systemsettings VALUES(81, 'Kikuyu', 'ki', 1);
INSERT INTO systemsettings VALUES(82, 'Kuanyama', 'kj', 1);
INSERT INTO systemsettings VALUES(83, 'Kazakh', 'kk', 1);
INSERT INTO systemsettings VALUES(84, 'Greenlandic', 'kl', 1);
INSERT INTO systemsettings VALUES(85, 'Cambodian', 'km', 1);
INSERT INTO systemsettings VALUES(86, 'Kannada', 'kn', 1);
INSERT INTO systemsettings VALUES(87, 'Korean', 'ko', 1);
INSERT INTO systemsettings VALUES(88, 'Konkani', 'kok', 1);
INSERT INTO systemsettings VALUES(89, 'Kanuri', 'kr', 1);
INSERT INTO systemsettings VALUES(90, 'Kashmiri', 'ks', 1);
INSERT INTO systemsettings VALUES(91, 'Kurdish', 'ku', 1);
INSERT INTO systemsettings VALUES(92, 'Komi', 'kv', 1);
INSERT INTO systemsettings VALUES(93, 'Cornish', 'kw', 1);
INSERT INTO systemsettings VALUES(94, 'Kirghiz', 'ky', 1);
INSERT INTO systemsettings VALUES(95, 'Latin', 'la', 1);
INSERT INTO systemsettings VALUES(96, 'Luxembourgish', 'lb', 1);
INSERT INTO systemsettings VALUES(97, 'Ganda', 'lg', 1);
INSERT INTO systemsettings VALUES(98, 'Limburgan', 'li', 1);
INSERT INTO systemsettings VALUES(99, 'Lingala', 'ln', 1);
INSERT INTO systemsettings VALUES(100, 'Laothian', 'lo', 1);
INSERT INTO systemsettings VALUES(101, 'Lithuanian', 'lt', 1);
INSERT INTO systemsettings VALUES(102, 'Luba-Katanga', 'lu', 1);
INSERT INTO systemsettings VALUES(103, 'Latvian', 'lv', 1);
INSERT INTO systemsettings VALUES(104, 'Malagasy', 'mg', 1);
INSERT INTO systemsettings VALUES(105, 'Marshallese', 'mh', 1);
INSERT INTO systemsettings VALUES(106, 'Maori', 'mi', 1);
INSERT INTO systemsettings VALUES(107, 'Macedonian', 'mk', 1);
INSERT INTO systemsettings VALUES(108, 'Malayalam', 'ml', 1);
INSERT INTO systemsettings VALUES(109, 'Mongolian', 'mn', 1);
INSERT INTO systemsettings VALUES(110, 'Moldavian', 'mo', 1);
INSERT INTO systemsettings VALUES(111, 'Marathi', 'mr', 1);
INSERT INTO systemsettings VALUES(112, 'Malay', 'ms', 1);
INSERT INTO systemsettings VALUES(113, 'Maltese', 'mt', 1);
INSERT INTO systemsettings VALUES(114, 'Burmese', 'my', 1);
INSERT INTO systemsettings VALUES(115, 'Nauru', 'na', 1);
INSERT INTO systemsettings VALUES(116, 'Norwegian Bokmal', 'nb', 1);
INSERT INTO systemsettings VALUES(117, 'Ndebele, North', 'nd', 1);
INSERT INTO systemsettings VALUES(118, 'Nepali', 'ne', 1);
INSERT INTO systemsettings VALUES(119, 'Ndonga', 'ng', 1);
INSERT INTO systemsettings VALUES(120, 'Dutch', 'nl', 1);
INSERT INTO systemsettings VALUES(121, 'Norwegian Nynorsk', 'nn', 1);
INSERT INTO systemsettings VALUES(122, 'Norwegian', 'no', 1);
INSERT INTO systemsettings VALUES(123, 'Ndebele, South', 'nr', 1);
INSERT INTO systemsettings VALUES(124, 'Sotho, Northern', 'nso', 1);
INSERT INTO systemsettings VALUES(125, 'Navajo', 'nv', 1);
INSERT INTO systemsettings VALUES(126, 'Chichewa', 'ny', 1);
INSERT INTO systemsettings VALUES(127, 'Occitan', 'oc', 1);
INSERT INTO systemsettings VALUES(128, 'Ojibwa', 'oj', 1);
INSERT INTO systemsettings VALUES(129, 'Oromo', 'om', 1);
INSERT INTO systemsettings VALUES(130, 'Oriya', 'or', 1);
INSERT INTO systemsettings VALUES(131, 'Ossetian', 'os', 1);
INSERT INTO systemsettings VALUES(132, 'Punjabi', 'pa', 1);
INSERT INTO systemsettings VALUES(133, 'Pali', 'pi', 1);
INSERT INTO systemsettings VALUES(134, 'Polish', 'pl', 1);
INSERT INTO systemsettings VALUES(135, 'Pashto', 'ps', 1);
INSERT INTO systemsettings VALUES(136, 'Portuguese', 'pt', 1);
INSERT INTO systemsettings VALUES(137, 'Quechua', 'qu', 1);
INSERT INTO systemsettings VALUES(138, 'Rhaeto-Romanic', 'rm', 1);
INSERT INTO systemsettings VALUES(139, 'Kirundi', 'rn', 1);
INSERT INTO systemsettings VALUES(140, 'Romanian', 'ro', 1);
INSERT INTO systemsettings VALUES(141, 'Russian', 'ru', 1);
INSERT INTO systemsettings VALUES(142, 'Kinyarwanda', 'rw', 1);
INSERT INTO systemsettings VALUES(143, 'Sanskrit', 'sa', 1);
INSERT INTO systemsettings VALUES(144, 'Sardinian', 'sc', 1);
INSERT INTO systemsettings VALUES(145, 'Sindhi', 'sd', 1);
INSERT INTO systemsettings VALUES(146, 'Northern Sami', 'se', 1);
INSERT INTO systemsettings VALUES(147, 'Sangro', 'sg', 1);
INSERT INTO systemsettings VALUES(148, 'Singhalese', 'si', 1);
INSERT INTO systemsettings VALUES(149, 'Slovak', 'sk', 1);
INSERT INTO systemsettings VALUES(150, 'Slovenian', 'sl', 1);
INSERT INTO systemsettings VALUES(151, 'Samoan', 'sm', 1);
INSERT INTO systemsettings VALUES(152, 'Shona', 'sn', 1);
INSERT INTO systemsettings VALUES(153, 'Somali', 'so', 1);
INSERT INTO systemsettings VALUES(154, 'Albanian', 'sq', 1);
INSERT INTO systemsettings VALUES(155, 'Serbian', 'sr', 1);
INSERT INTO systemsettings VALUES(156, 'Siswati', 'ss', 1);
INSERT INTO systemsettings VALUES(157, 'Sotho, Southern', 'st', 1);
INSERT INTO systemsettings VALUES(158, 'Sudanese', 'su', 1);
INSERT INTO systemsettings VALUES(159, 'Swedish', 'sv', 1);
INSERT INTO systemsettings VALUES(160, 'Swahili', 'sw', 1);
INSERT INTO systemsettings VALUES(161, 'Tamil', 'ta', 1);
INSERT INTO systemsettings VALUES(162, 'Telugu', 'te', 1);
INSERT INTO systemsettings VALUES(163, 'Tajik', 'tg', 1);
INSERT INTO systemsettings VALUES(164, 'Thai', 'th', 1);
INSERT INTO systemsettings VALUES(165, 'Tigrinya', 'ti', 1);
INSERT INTO systemsettings VALUES(166, 'Tigre', 'tig', 1);
INSERT INTO systemsettings VALUES(167, 'Turkmen', 'tk', 1);
INSERT INTO systemsettings VALUES(168, 'Tagalog', 'tl', 1);
INSERT INTO systemsettings VALUES(169, 'Klingon', 'tlh', 1);
INSERT INTO systemsettings VALUES(170, 'Tswana', 'tn', 1);
INSERT INTO systemsettings VALUES(171, 'Tonga', 'to', 1);
INSERT INTO systemsettings VALUES(172, 'Turkish', 'tr', 1);
INSERT INTO systemsettings VALUES(173, 'Tsonga', 'ts', 1);
INSERT INTO systemsettings VALUES(174, 'Tatar', 'tt', 1);
INSERT INTO systemsettings VALUES(175, 'Twi', 'tw', 1);
INSERT INTO systemsettings VALUES(176, 'Tahitian', 'ty', 1);
INSERT INTO systemsettings VALUES(177, 'Uighur', 'ug', 1);
INSERT INTO systemsettings VALUES(178, 'Ukrainian', 'uk', 1);
INSERT INTO systemsettings VALUES(179, 'Urdu', 'ur', 1);
INSERT INTO systemsettings VALUES(180, 'Uzbek', 'uz', 1);
INSERT INTO systemsettings VALUES(181, 'Venda', 've', 1);
INSERT INTO systemsettings VALUES(182, 'Vietnamese', 'vi', 1);
INSERT INTO systemsettings VALUES(183, 'Volapuck', 'vo', 1);
INSERT INTO systemsettings VALUES(184, 'Walloon', 'wa', 1);
INSERT INTO systemsettings VALUES(185, 'Sorbian', 'wen', 1);
INSERT INTO systemsettings VALUES(186, 'Wolof', 'wo', 1);
INSERT INTO systemsettings VALUES(187, 'Xhosa', 'xh', 1);
INSERT INTO systemsettings VALUES(188, 'Yiddish', 'yi', 1);
INSERT INTO systemsettings VALUES(189, 'Yoruba', 'yo', 1);
INSERT INTO systemsettings VALUES(190, 'Zhuang', 'za', 1);
INSERT INTO systemsettings VALUES(191, 'Chinese', 'zh', 1);
INSERT INTO systemsettings VALUES(192, 'Zulu', 'zu', 1);

INSERT INTO systemsettings VALUES('1000', 'unidentified browser', 'unidentified browser',  2);
INSERT INTO systemsettings VALUES('1001', 'Mozilla 1.0+','Mozilla/5.0',   2);
INSERT INTO systemsettings VALUES('1002', 'IE 5.5+','MSIE',   2);
INSERT INTO systemsettings VALUES('1003', 'IE 5.2 (Mac)','MSIEMAC',   2);
INSERT INTO systemsettings VALUES('1004', 'Safari (Mac)','Safari',   2);
INSERT INTO systemsettings VALUES('1005', 'Mozilla FireFox','Firefox',   2);
INSERT INTO systemsettings VALUES('1006', 'Opera 7.5+','Opera 7.54',   2);

INSERT INTO systemsettings VALUES('2000', 'unidentified operating system', 'unidentified operating system',  3);
INSERT INTO systemsettings VALUES('2001', 'Windows', 'Windows',  3);
INSERT INTO systemsettings VALUES('2002', 'Linux', 'Linux',  3);
INSERT INTO systemsettings VALUES('2003', 'Mac', 'Mac',  3);
