document.writeln('{HTML_SOURCE_REQUEST_PARAM_KEY}');
var rnd = Math.round(Math.random() * 10000000);
var im = '{ONUNLOADHANDLER_REQUEST_PARAM_KEY}';
document.writeln('<SC' + 'RIPT language=JavaScript type=text/javascript>');
document.writeln('var fun' + rnd + ' = window.onunload;');
document.writeln('window.onunload = ads_fun' + rnd + ';');
document.writeln('function ads_fun' + rnd + '() {');
document.writeln('document.getElementById("{id}").src=im;');
document.writeln('if (fun' + rnd + ') fun' + rnd + '();}');
document.writeln('</SC' + 'RIPT>');